# Generated by Django 2.2 on 2019-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='accu_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='accu_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='accu_rtoken',
            field=models.IntegerField(default=0),
        ),
    ]
