# Generated by Django 2.2 on 2019-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190518_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='accu_comment_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='accu_likes_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='accu_rtoken_percentage',
            field=models.FloatField(default=0),
        ),
    ]
