# Generated by Django 2.2 on 2019-05-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190518_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='accu_comment_percentage',
            new_name='accu_comment_likes_percentage',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='accu_likes_percentage',
            new_name='accu_quest_likes_percentage',
        ),
    ]
