# Generated by Django 2.2 on 2019-05-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190518_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='accu_comment',
            new_name='accu_comment_likes',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='accu_likes',
            new_name='accu_quest_likes',
        ),
    ]
