# Generated by Django 2.1.7 on 2019-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_remove_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='image'),
        ),
    ]
