# Generated by Django 2.1.7 on 2019-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0004_auto_20190513_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, height_field=500, upload_to='image', width_field=900),
        ),
    ]
