# Generated by Django 2.1.7 on 2019-05-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0005_auto_20190513_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
