# Generated by Django 2.2 on 2019-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0006_auto_20190513_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursework_marks', models.FloatField(default=0.0)),
                ('marks_wanted', models.FloatField(default=0.0)),
                ('final_marks', models.FloatField(default=0.0)),
            ],
        ),
    ]
