# Generated by Django 2.2 on 2019-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0007_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
