# Generated by Django 2.2 on 2019-05-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0010_remove_comment_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calculator',
        ),
    ]
