# Generated by Django 2.1.7 on 2019-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0011_delete_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
